<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	<PackAsTool>true</PackAsTool>
	<ToolCommandName>blazr</ToolCommandName>
	<PackageOutputPath>./nupkg</PackageOutputPath>
	<PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Commands\**\*.cs" />
    <Compile Include="Services\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="Spectre.Console" Version="0.53.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
  </ItemGroup>

</Project>
